version: '3.8'

services:
  api:
    image: restapi:latest
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`restapi.agenteaiteste.shop`)
        - traefik.http.routers.api.entrypoints=websecure
        - traefik.http.routers.api.tls.certresolver=letsencrypt
        - traefik.http.services.api.loadbalancer.server.port=5000
    networks:
      - AgenteAIteste

networks:
  AgenteAIteste:
    external: true