version: '3.8'

services:
  api:
    build: .
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`restapi.agenteaiteste.shop`)
        - traefik.http.routers.api.tls=true
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true